				</div>
			</div>
			<!--footer -->
			<div id="footer">
				<div class="left">
					<div class="menu">
						<a href="/">Home</a> &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;&nbsp;
						<a href="/vendors">Vendors</a> &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;&nbsp;
						<a href="/inventory">Inventory</a> &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;&nbsp;
						<a href="/purchases">Purchases</a>&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;&nbsp;
						<a href="/sales">Sales</a> &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;&nbsp;
						<a href="/reports">Reports</a> &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;&nbsp;
						<a href="/discounts">Discounts</a>
					</div>
					IMS &copy; 2010<br />
				
				</div>
				<div class="right">
					<img alt="" src="images/linux.gif" /><img alt="" src="images/mysql.png" /><img alt="" src="images/php.png" /><img alt="" src="images/zend.png" /><br />
			  </div>
				<div class="clear"></div>
			</div>
			<!--footer end-->
		</div>
	</div>
</body>
</html>
