{include file="header.phtml" section="home"}
<div class="cols">
	<div class="col1">
		<div class="padding">
			<a href="/vendors"><img alt="" src="images/vendors.png" class="imgindent" /></a>
			<strong>Vendors Management</strong><br />
			This part is to manage the vendors of the store. Functionalities include Add and Update a vendor.<br class="clear" />
			<a href="/purchases"><img alt="" src="images/purchases.png" class="imgindent" /></a>
			<strong>Purchases Management</strong><br />
			This part is to manage the purchases of the store. Functionaltities include Place Order, View Received Orders and View Pending Orders.<br class="clear" />
			<a href="/reports"><img alt="" src="images/report.png" class="imgindent" /></a>
			<strong>Reports</strong><br />
			This part is to manage the reports of the store. Functionalities include View Total Sales Report, View Total Purchases Report, and View Prediction Report.<br class="clear" />
	  </div>
	</div>
	<div class="col2">
		<a href="/inventory"><img alt="" src="images/inventory.png" class="imgindent" /></a>
		<strong>Inventory Management</strong><br />
		This part is to manage the store inventory. Functionalities include View Current Inventory by Items or by Vendors and Search for an item.<br class="clear" />
		<a href="/sales"><img alt="" src="images/sales.png" class="imgindent" /></a>
		<strong>Sales Management</strong><br />
		This part is to manage the sales of the store. Functionalities include Create Bill and View Bills.<br class="clear" />
		<img alt="" src="images/about.png" class="imgindent" />
		<strong>Discount Management</strong><br />
		This part is to manage seasonal and coupon discount. Functionalities include Add/Modify/Remove Seasonal/Coupon.<br class="clear" />
	</div>
	<div class="clear"></div>
</div>
{include file="footer.phtml"}
